# Generated by Django 2.0 on 2018-01-24 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_auto_20180120_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 26, 14, 35, 8, 330650, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
