# Generated by Django 2.1 on 2019-02-27 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_auto_20180124_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 12, 1, 13, 592904, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
